### PR TITLE
Add ForestFire model for MASON

### PR DESCRIPTION
**Pull request by Tortar**
This is a modified version of ForestFire which should be in line with the other implementations as discussed in #31. 

One thing I'm doing (and I did also for the other models) is to have two different files for the small and the large versions, if you have any idea on how to make it possible to have only one file let me know, the fact is that I wasn't able to find a way to pass parameters from the bash benchmark file to the mason model so I specified them inside the class

### CODE REVIEW

**Comment by Datseris** [comment]
This PR deletes many files in other folders, is this intended?

No, there doesn't seem to be a way to have one file, this seems to be one of the many clunkiness-es of MASON.

**Comment by Tortar** [comment]
yes, it's intended, they are compiled files which now are ignored in .gitignore, they are created when the benchmark run with `javac` command

**Review by Datseris — APPROVED** [review]
BTW, have you learned how to obtain the "video output" for MASON? So that we can just "look" that the output is as what we expect... 

Don't worry if you cant get video output, we do not care too much about putting too much time on MASON.

**Comment by Tortar** [comment]
Didn't look into it till now, I think it would be better to have it but I think it would take be a bit of time to understand and implement the video version, and I have to say I'm running out of time since I have some work to do for my Uni also in this moment :-)

**Pull request merged**
