### PR TITLE
Use Int8 instead of Int in Agents.jl ForestFire

### PR DESCRIPTION
**Pull request by Tortar**
#61

### CODE REVIEW

**Comment by Datseris** [comment]
I am not sure if such an optimization makes sense, in the sense that it can be trivially be done across all frameworks and it would have the same impact; here we used Int8 only in Agents.jl. If there is a reason to specify the type of the container we might as well declare it in the decleration file

**Comment by Tortar** [comment]
I don't think it is true, NetLogo can't specify the type of integers so I think such an optimizations is not possible, Mason and Mesa can't do it too with the current implementation which means that it is not a trivial change

**Comment by Tortar** [comment]
So I would instead declare that as you suggested

**Comment by Datseris** [comment]
it is so crazy sad that such a trivial, simple change as changing the element type of a container is difficult in other frameworks.

**Pull request merged**
