### PR TITLE
Make Schelling comparison fairer

### PR DESCRIPTION
**Pull request by Tortar**
We shouldn't early exit in Agents.jl since it isn't done elsewhere as pointed out in #57

### CODE REVIEW

**Comment by Tortar** [comment]
Seems like a very big slowdown, but that's life

**Comment by Datseris** [comment]
Does MASON has the skip clause?

**Comment by Tortar** [comment]
it hasn't any skip clause but I'm actually noticing another problem with the MASON implementation which gives it an unfair advantage: it uses a cellular automata approach, so we should restructure it anyway

**Comment by Datseris** [comment]
Okay, but then we should do this in this PR, right?

**Comment by Tortar** [comment]
yes will add it here :-)

**Comment by Tortar** [comment]
Everything should be done!

**Pull request merged**
