### PR TITLE
Seed models

### PR DESCRIPTION
**Pull request by Tortar**
All models for Agents, Mesa and Mason are now seeded! but I still need to do the same with NetLogo

### CODE REVIEW

**Comment by Datseris** [comment]
how is the seed provided when the models are run?

**Comment by Tortar** [comment]
the seed is provided by another random number generator seeded with a value equal to 42, each time the model is run we use a different random integer (from 1 to 10000) provided by this rng. Everything should be fine I think, let me know if you think otherwise

**Comment by Datseris** [comment]
Ok that's perfect. You do this for all frameworks right ? How many different rngs are run?

**Comment by Tortar** [comment]
NetLogo is still missing: with NetLogo is a bit more difficult since we can't pass anything from the outside, but I found a sound strategy to use I think but will implement it tomorrow.

For each model benchmark two rngs are used as I described. However, the first rng used to seed the one used in the model benchmark is different for each framework: a MersenneTwister for Agents, another MT for Python (but I think implemented a bit differently than in Julia) and one provided by Bash but for which I didn't check its nature actually

**Comment by Tortar** [comment]
Take Flocking benchmark, before:

```julia
using Agents
using BenchmarkTools

include("Flocking.jl")

a = @benchmark step!(model, agent_step!, model_step!, 100) setup = (
    (model, agent_step!, model_step!) = flocking()) samples=100

println("Agents.jl Flocking (ms): ", minimum(a.times) * 1e-6)
```

after (with some comments):

```julia
using Agents
using BenchmarkTools
using Random

include("Flocking.jl")

rng_seed = MersenneTwister(42) # here we instantiate a rng which is only used to create some seeds for the actual rng used in the model

# a Xhoshiro rng is used inside the model, it is seeded by the rng above
a = @benchmark step!(model, agent_step!, model_step!, 100) setup = 
    ((model, agent_step!, model_step!) = flocking(Xoshiro(rand(rng_seed, 1:10000)))) evals=1 samples=100 

println("Agents.jl Flocking (ms): ", minimum(a.times) * 1e-6)
```

As you can see we run @benchmark with samples=100 and evals=1, so in each of the 100 runs the models uses a differently seeded rng. With all other frameworks the way all works is the same except that the rng for seeding changes.

**Comment by Tortar** [comment]
oh my god, what a hard time working with NetLogo x(

Now everything *should* be fine, let's see it the benchmarks run

**Comment by Tortar** [comment]
It worked!!!!

**Pull request merged**
