### PR TITLE
Fix flocking behaviour

### LINKED ISSUE #72: Boundary condition in Flockers?
Sorry, its me again. I am now looking at the comparison between agents.jl and mesa for the flockers model. 

Quite some time for mesa is spent on handling the torus adjustments, what is more formally called periodic boundary condition in agents.jl. And I think here something is off with the Agents.jl implementation. I haven't run the agents.jl version locally but looking at animation on the docs page (https://juliadynamics.github.io/Agents.jl/stable/examples/flock/) I observed the following:

Agents should cross boundaries and appear on the other side. However, this seems to only work for single agents. Flock of agents bounce of the wall, probably due to how headings and coherence is modeled. But this shouldn't happen.

### PR DESCRIPTION
**Pull request by Tortar**
Fixes #72

### CODE REVIEW

**Comment by Datseris** [comment]
Do the animations also match the behavior one would expect?

**Comment by Datseris** [comment]
yes it does. Thanks. THen please also make a similar PR to the Agents.jl example as this is the model we use for contnuous space?

**Review by Datseris — APPROVED** [review]
Go ahead and merge!

**Comment by Tortar** [comment]
yes, sure I will do a similar pr there :-)

**Pull request merged**
