### PR TITLE
Add WolfSheep for Mason

### PR DESCRIPTION
**Pull request by Tortar**
Addressing #31. this needs to be rewritten to some extent before merging for making it equivalent to the ones in the other frameworks

### CODE REVIEW

**Comment by Tortar** [comment]
What I'm noticing is that they have a bit more performant implementation than ours in a sense: they are using two different grids, one for Wolfs, and one for Sheeps. I don't think we actually support this at the moment since we don't support multi-space models at the moment, do you think this could be a good addition @Datseris ?

**Comment by Tortar** [comment]
Everything should be good, I will update the readme table with the new addition, let me know if everything seems allright to you

**Comment by Datseris** [comment]
Everythong does seem alright. Once we have https://github.com/JuliaDynamics/Agents.jl/issues/809 we can even simplify our implementation further.

**Comment by Tortar** [comment]
there were a lot of differences...I'm wondering how they managed to run the comparison without any comparability...What about multi-space models? What do you think about it?

**Pull request merged**
