### PR TITLE
Start up netlogo faster

### LINKED ISSUE #47: Speed-up NetLogo benchmarks start-up
We shouldn't start-up `netlogo-headless` for each repetition because it takes nearly 20 secs each time as discussed in #46.

We could do so by providing all seeds at once at start-up as it is done here with the variable `number`:

```xml
<experiments>
  <experiment name="understand_xml" repetitions="1" runMetricsEveryStep="true">
    <setup>setup</setup>
    <go>go</go>
    <metric>count turtles</metric>
    <enumeratedValueSet variable="color-by">
      <value value="&quot;success&quot;"/>
    </enumeratedValueSet>
    <enumeratedValueSet variable="memory">
      <value value="6"/>
    </enumeratedValueSet>
    <enumeratedValueSet variable="number">
      <value value="593"/>
      <value value="344"/>
      <value value="442"/>
    </enumeratedValueSet>
    <enumeratedValueSet variable="strategies-per-agent">
      <value value="5"/>
    </enumeratedValueSet>
  </experiment>
</experiments>
```

and we should also change the way timings are retrieved from the .txt file created by Netlogo due to the new way of doing the benchmark.

### PR DESCRIPTION
**Pull request by Tortar**
This hopefully should resolve #47

### CODE REVIEW

**Comment by Tortar** [comment]
The benchmarks now finish in 1/2 of the time. 

Notably NetLogo is now faster at running the benchmarks, particularly the small versions. Not sure how to explain this fact but a possible reason is that the restarting of NetLogo in the earlier benchmarks could then create a bit of latency for the first run

**Review by Datseris — COMMENTED** [review]
I don't have any meaningful expertise in NetLogo to review this unfortunately. You have to either merge or request feedback from netlogo developers. Or we hope that they will start doing pull requests on their own at some point as we've notified them of the existence of this repo. 

But this is a huge reduction in NetLogo benchmark speed. What have we actually changed? What does this "startup time" entail?

**Comment by Tortar** [comment]
This new timings are strange to me too, I didn't change anything inside the NetLogo models, but one way to explain this is that using this new methodology we don't open and close NetLogo for each run, and since NetLogo is built in Java and that Java has a so called "warm-up time" where the jvm understands how to optimize the code after some initial runs, it is possible that this can be the reason for these new timings.

@LaCuneta , saw that you are actively developing NetLogo, have you any explanation for this behaviour? :-)

**Comment by Tortar** [comment]
Anyway I think this is mostly legitimate so I merge

**Pull request merged**
