### PR TITLE
CI setup

### PR DESCRIPTION
**Pull request by Tortar**
Configured a CI version of the benchmarks. Probably there is a lot to improve since I'm inexperienced with CI configuration, but it works. The way it is done as of now is to use a newly created `setup.sh` benchmark file for setting up the benchmark and then run `runall.sh`. The first file is a simple modification of the script in the section "how to run the benchmarks locally". 

Probably a first improvement would be posting the final table in some different section on CI where it's more easily to see, currently it is in the last lines of "Run bash ./.github/setup.sh".

What do you think @Datseris ?

### CODE REVIEW

**Comment by Tortar** [comment]
Also, let's see the time it will take to finish the benchmark, in particular NetLogo is **very slow** at running the benchmarks, since it needs to restart the headless version each time, which requires a lot of time

**Comment by Tortar** [comment]
Also, Mason models appears to be seeded, we should change it

**Comment by Datseris** [comment]
that's great. where is this table stored? is it printed during CI?

**Comment by Tortar** [comment]
It's printed during CI, for now it is not stored anywhere, I need to figure out how to do it, if you have any idea, please share them with me :-)

**Comment by Datseris** [comment]
Yeah I am not sure exactly how to make this work. I know that Documenter.jl does it, because it saves the created webpages. But how , I don't know. You should post a question on Discourse and tag me there as well!

**Comment by Datseris** [comment]
I am merging this in now because it is a first successful step!

**Pull request merged**
